version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    environment:
      - NODE_ENV=production
    command: sh -c "pnpm run db:init && pnpm run build && pnpm start"

  app-dev:
    build: .
    ports:
      - "3000:3000"
      - "1883:1883"
      - "9001:9001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "pnpm run db:init && pnpm run dev"